version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5430:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - postgres_network

volumes:
  db_data:

networks:
  postgres_network:
